Fix cards
neo4j-documentation/docs-ui pull request #288
Opened 2024-12-17 13:50 UTC by lidiazuin

2024-12-19 11:16 UTC, recrwplay requested changes

2024-12-19 12:11 UTC, lidiazuin commented on src/css/docs-ndl.css
> +  display: flex;
The "Keep learning" headers? Or maybe this is for something else than that?

2024-12-19 12:14 UTC, lidiazuin commented on src/css/docs-ndl.css
> +  font-size: 0;
No, it doesn't work without the .hide subclass. If I use your suggestion, it hides the links from the non-selectable cards too, even if I keep the following lines intact

2024-12-19 12:15 UTC, lidiazuin commented on preview-src/docs-hub.adoc
How do you separate the types of cards in the .adoc file? Like, the styling keeps on being applied after one card. I tried putting the card into `--` separators, but it didn't work.

2024-12-19 13:47 UTC, recrwplay commented on src/css/docs-ndl.css
> +  display: flex;
It's displaying headers that we currently don't display - check the preview - https://deploy-preview-288--neo4j-docs-ui.netlify.app/docs-ndl - "Getting started" " CTA cards" etc. None of these should be visible

2024-12-19 14:05 UTC, lidiazuin commented on src/css/docs-ndl.css
> +  display: flex;
Ah ok, so I will create another class for Keep learning

2024-12-20 13:38 UTC, recrwplay commented on src/css/docs-ndl.css
> +  display: flex;
Headers looks fixed to me now 👍🏻

2024-12-20 13:41 UTC, recrwplay commented on src/css/docs-ndl.css
> +  font-size: 0;
I think this is fixed in the css now 👍🏻

2025-01-14 13:12 UTC, recrwplay approved these changes

2025-01-14 13:16 UTC, merged